# Generated by Django 2.0.3 on 2018-03-18 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birth_data',
            field=models.DateField(blank=True, verbose_name='Data de nascimento'),
        ),
    ]
