# Generated by Django 2.0.3 on 2018-03-18 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20180317_2222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cpf',
            field=models.CharField(max_length=15, verbose_name='CPF'),
        ),
    ]
