# Generated by Django 2.0.3 on 2018-03-20 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20180319_2138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Telefone de contato'),
        ),
    ]
