# Generated by Django 2.0.3 on 2018-03-21 03:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0006_auto_20180320_2330'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Buy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purshases', to=settings.AUTH_USER_MODEL, verbose_name='Comprador')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buy.Buy')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.Gear', verbose_name='peça')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_order', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitacoes', to='core.Gear', verbose_name='peça')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitacoes', to=settings.AUTH_USER_MODEL, verbose_name='solicitante')),
            ],
        ),
        migrations.CreateModel(
            name='Pay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_pay', models.CharField(choices=[('cartao', 'Cartão'), ('em especie', 'Em espécie'), ('por boleto', 'Por boleto')], default='Em especie', max_length=20)),
                ('total_value', models.DecimalField(decimal_places=2, max_digits=5)),
                ('date_pay', models.DateTimeField(auto_now_add=True, verbose_name='Data de pagamento')),
                ('buy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagamento', to='buy.Buy', verbose_name='Compra')),
            ],
        ),
    ]
