# Generated by Django 2.0.3 on 2018-03-21 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buy', '0003_auto_20180321_0951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buy',
            name='amount_items',
            field=models.IntegerField(default=0, verbose_name='Quantidade de itens'),
        ),
    ]
