# Generated by Django 2.0.3 on 2018-03-21 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buy', '0005_auto_20180321_1025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='buy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='buy.Buy'),
        ),
    ]
