# Generated by Django 2.0.3 on 2018-03-21 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buy', '0006_auto_20180321_1027'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='amount',
            field=models.IntegerField(default=0, verbose_name='Quantidade'),
        ),
    ]
