# Generated by Django 2.0.3 on 2018-03-22 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buy', '0007_item_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buy',
            name='status',
            field=models.CharField(choices=[('open', 'Aberta'), ('closed', 'Fechada')], default='open', max_length=5),
        ),
    ]
