# Generated by Django 2.0.3 on 2018-03-22 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buy', '0009_auto_20180322_0954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='amount',
            field=models.IntegerField(default=0, verbose_name='Quantidade'),
        ),
    ]
