# Generated by Django 2.0.3 on 2018-03-20 02:41

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Automaker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_descr', models.CharField(max_length=60, verbose_name='Nome da montadora')),
                ('number', models.CharField(blank=True, max_length=15, verbose_name='Telefone de contato')),
                ('email', models.CharField(max_length=50, unique=True, verbose_name='E-mail')),
            ],
        ),
        migrations.CreateModel(
            name='Gear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_descr', models.CharField(max_length=60, verbose_name='Nome da peça')),
                ('type_gear', models.CharField(choices=[('acessórios', 'Acessórios'), ('pneus', 'Pneus, Rodas e Calotas'), ('iluminação', 'Faróis, Lanteras e iluminação'), ('midia', 'Som e Vídeo'), ('segurança', 'Alarmes e segurança'), ('grades', 'Para-choques e Grades'), ('motocicletas', 'Motocicletas')], default='Sem tipo', max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Modelo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_descr', models.CharField(max_length=60, verbose_name='Nome do modelo')),
                ('year', models.IntegerField(validators=[django.core.validators.MaxValueValidator(3000)])),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_descr', models.CharField(max_length=60, verbose_name='Nome do veiculo')),
                ('automaker', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='veiculos', to='core.Automaker', verbose_name='Montadora')),
            ],
        ),
        migrations.AddField(
            model_name='modelo',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modelo', to='core.Vehicle', verbose_name='Veiculo'),
        ),
        migrations.AddField(
            model_name='gear',
            name='modelo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pecas', to='core.Modelo'),
        ),
    ]
