# Generated by Django 2.0.3 on 2018-03-20 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gear',
            name='amount',
            field=models.IntegerField(blank=True, default=0, verbose_name='Quantidade em estoque'),
        ),
        migrations.AddField(
            model_name='gear',
            name='views',
            field=models.IntegerField(blank=True, default=0, verbose_name='Visualizações'),
        ),
    ]
