# Generated by Django 2.0.3 on 2018-03-20 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20180320_0812'),
    ]

    operations = [
        migrations.AddField(
            model_name='gear',
            name='thumb',
            field=models.ImageField(blank=True, default='default.jpg', upload_to=''),
        ),
    ]
