# Generated by Django 2.0.3 on 2018-03-20 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20180320_0859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gear',
            name='thumb',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='core/images'),
        ),
    ]
