# Generated by Django 2.0.3 on 2018-03-21 02:30

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20180320_1149'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gear',
            options={'verbose_name': 'Peça', 'verbose_name_plural': 'Peças'},
        ),
        migrations.AlterField(
            model_name='gear',
            name='modelo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pecas', to='core.Modelo', verbose_name='Modelo da peça'),
        ),
        migrations.AlterField(
            model_name='gear',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Preço'),
        ),
        migrations.AlterField(
            model_name='gear',
            name='thumb',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='core/images', verbose_name='Imagem representativa'),
        ),
        migrations.AlterField(
            model_name='gear',
            name='type_gear',
            field=models.CharField(choices=[('acessórios', 'Acessórios'), ('pneus', 'Pneus, Rodas e Calotas'), ('iluminação', 'Faróis, Lanteras e iluminação'), ('midia', 'Som e Vídeo'), ('segurança', 'Alarmes e segurança'), ('grades', 'Para-choques e Grades'), ('motocicletas', 'Motocicletas'), ('sem_tipo', 'Sem tipo')], default='sem_tipo', max_length=20, verbose_name='Tipo da peça'),
        ),
        migrations.AlterField(
            model_name='modelo',
            name='year',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(3000)], verbose_name='Ano do modelo'),
        ),
    ]
