# Generated by Django 2.0.3 on 2018-03-22 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20180320_2330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gear',
            name='price',
            field=models.FloatField(verbose_name='Preço da peça'),
        ),
    ]
